In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df_1 = pd.read_csv('train.csv')
df_2 = pd.read_csv('test.csv')

In [3]:
df_com = pd.concat([df_1, df_2], ignore_index=True)

In [4]:
df_com

,profile pic,nums/length username,fullname words,nums/length fullname,name==username,description length,external URL,private,#posts,#followers,#follows,fake
0,1,0.27,0,0.0,0,53,0,0,32,1000,955,0
1,1,0.00,2,0.0,0,44,0,0,286,2740,533,0
2,1,0.10,2,0.0,0,0,0,1,13,159,98,0
3,1,0.00,1,0.0,0,82,0,0,679,414,651,0
4,1,0.00,2,0.0,0,0,0,1,6,151,126,0
...,...,...,...,...,...,...,...,...,...,...,...,...
691,1,0.29,1,0.0,0,0,0,0,13,114,811,1
692,1,0.40,1,0.0,0,0,0,0,4,150,164,1
693,1,0.00,2,0.0,0,0,0,0,3,833,3572,1
694,0,0.17,1,0.0,0,0,0,0,1,219,1695,1
695,1,0.44,1,0.0,0,0,0,0,3,39,68,1

In [49]:
label_col = 'fake'
features = df_com.drop(columns=[label_col])
label = df_com[label_col]

scaler = StandardScaler()
scaler.fit(features)
normalized_features = scaler.transform(features)
df_normalized = pd.DataFrame(normalized_features, columns=features.columns)

df_normalized[label_col] = label
df_normalized.to_csv('comb_Z_score.csv', index=False)

print("ì™„ë£Œ")

ì™„ë£Œ

In [27]:
x_bot_df = pd.read_csv('bot_user_data.csv')
x_human_df = pd.read_csv("x_user_data.csv")

In [29]:
x_comb_df = pd.concat([x_bot_df, x_human_df], ignore_index=True)

In [41]:
x_features = x_comb_df.drop(columns = [label_col])
x_normalized_features = scaler.transform(x_features)

In [43]:
label = x_comb_df[label_col]

In [45]:
x_df_normalized = pd.DataFrame(x_normalized_features, columns=features.columns)

In [51]:
df_normalized[label_col] = label
df_normalized.to_csv('x_Z_score.csv', index=False)